import iranSans from '@services/LocalFonts'
import './globals.css'
import Layout from '@/components/layout/Layout'






export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="fa" dir="rtl">
      <body className={iranSans.className} style={{ direction: "rtl" }}>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  )
}
