import iranSans from '@services/LocalFonts'
import './globals.css'
import Layout from '@/components/layout/Layout'
import { NextIntlClientProvider } from 'next-intl';

import { useLocale } from 'next-intl';
import { notFound } from 'next/navigation';



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children, params }) {
  const locale = useLocale()


  if (params.locale !== locale) {
    notFound();
  }

  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale} dir={locale === "en" ? "ltr" : "rtl"}>
      <body className={iranSans.className} >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Layout>
            {children}
          </Layout>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
